#!/bin/bash
set -eux # -x for verbose logging to juju debug-log
juju-log "Installing open jdk"
apt-get install -y default-jre-headless apache2

#install vbench
juju-log "Installing vdbench"
tar -xvf vdbench*.tar
cp /bin/bash /bin/csh
cp vdbench.bash vdbench
