#!/bin/bash
set -eux # -x for verbose logging to juju debug-log
if pidof -x vdbench > /dev/null
then
  juju-log "Vdbench already running"
else
  juju-log "Starting vdbench"
  ./vdbench -t
  open-port 80/tcp
  cp -a /var/lib/juju/units/vdbench*/charm/output/ /var/www/
  rm /var/www/index.html
fi
