#!/bin/bash
# Here put anything that is needed to start the service.
# Note that currently this is run directly after install
# i.e. 'service apache2 start'

#HOME=$(dirname $0)
#$HOME/vdbench -t

set -eux # -x for verbose logging to juju debug-log
juju-log "Starting vdbench"
./vdbench -t

