#!/bin/bash
set -eu # -x for verbose logging to juju debug-log
if pidof -x vdbench > /dev/null
then
  juju-log "Vdbench already running"
else
  juju-log "Starting vdbench"
  cd vdbench
  ./vdbench -t 
  open-port 80/tcp
  cp -a /var/lib/juju/units/vdbench*/charm/vdbench/output/ \
    /var/www/$(date +%F_%T)"_vdbench_output"	
  rm -rf /var/lib/juju/units/vdbench*/charm/vdbench/output
  rm /var/www/index.html
fi
